# Generated by Django 5.2.3 on 2025-06-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('CARDIOLOGY', 'Cardiology'), ('DERMATOLOGY', 'Dermatology'), ('ENDOCRINOLOGY', 'Endocrinology'), ('GASTROENTEROLOGY', 'Gastroenterology'), ('HEMATOLOGY', 'Hematology'), ('INFECTIOUS_DISEASE', 'Infectious Disease'), ('NEPHROLOGY', 'Nephrology'), ('NEUROLOGY', 'Neurology'), ('OBSTETRICS_GYNECOLOGY', 'Obstetrics & Gynecology'), ('ONCOLOGY', 'Oncology'), ('OPHTHALMOLOGY', 'Ophthalmology'), ('ORTHOPEDICS', 'Orthopedics'), ('OTOLARYNGOLOGY', 'Otolaryngology (ENT)'), ('PEDIATRICS', 'Pediatrics'), ('PSYCHIATRY', 'Psychiatry'), ('PULMONOLOGY', 'Pulmonology'), ('RHEUMATOLOGY', 'Rheumatology'), ('SURGERY', 'Surgery'), ('UROLOGY', 'Urology'), ('RADIOLOGY', 'Radiology'), ('ANESTHESIOLOGY', 'Anesthesiology'), ('EMERGENCY_MEDICINE', 'Emergency Medicine'), ('FAMILY_MEDICINE', 'Family Medicine'), ('GENETICS', 'Genetics'), ('GERIATRICS', 'Geriatrics'), ('IMMUNOLOGY', 'Immunology'), ('INTERNAL_MEDICINE', 'Internal Medicine'), ('OCCUPATIONAL_MEDICINE', 'Occupational Medicine'), ('PATHOLOGY', 'Pathology'), ('PHYSICAL_MED_REHAB', 'Physical Medicine & Rehabilitation'), ('PLASTIC_SURGERY', 'Plastic Surgery'), ('PREVENTIVE_MEDICINE', 'Preventive Medicine'), ('SPORTS_MEDICINE', 'Sports Medicine'), ('TRANSPLANT_SURGERY', 'Transplant Surgery'), ('TRAUMA_SURGERY', 'Trauma Surgery'), ('VASCULAR_SURGERY', 'Vascular Surgery')], null=True),
        ),
    ]
