# Generated by Django 5.2.3 on 2025-06-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='desc',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
