# Generated by Django 5.2.3 on 2025-06-16 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='patients/')),
                ('full_name', models.CharField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')])),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField(max_length=10)),
                ('relation_type', models.CharField(choices=[('SELF', 'Self'), ('FATHER', 'Father'), ('MOTHER', 'Mother'), ('BROTHER', 'Brother'), ('SISTER', 'Sister'), ('SPOUSE', 'Spouse'), ('SON', 'Son'), ('DAUGHTER', 'Daughter'), ('GRANDFATHER', 'Grandfather'), ('GRANDMOTHER', 'Grandmother'), ('UNCLE', 'Uncle'), ('AUNT', 'Aunt'), ('COUSIN', 'Cousin'), ('FRIEND', 'Friend'), ('OTHER', 'Other')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
